### ISSUE TITLE
Letters should appear on key down rather than up on the save screen

### ISSUE THREAD

**Issue by tremby** [OpenFodder/openfodder#85]
**Describe the bug**
On the save screen letters appear on key up rather than key down, which means unexpected text can appear when typing fast.

**To Reproduce**
1. Go to the "save" screen
2. Hold "a". Nothing appears.
3. Press and release "b". "B" appears.
4. Release "a". "A" appears.

(Note also that weird things happen if more than a couple of keys are down at once. I've seen doubled letters etc.

**Expected behavior**
Letters appear on key down rather than key up. I should end up with "AB" in the example above.

(I don't much care whether keys repeat after being held for a while or not. It'd be nice if it did whatever my OS is set to do I suppose, but as a user I wouldn't expect it.)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Version Ubuntu 22.04

**Additional context**

**Comment by segrax** [comment]
i have a vague memory of doing this on purpose, but no idea why. 

fix pushed, but only quickly tested

**Comment by tremby** [comment]
It works for me, big improvement. Thanks!

I do still get some weird behaviour -- I've seen doubled or missing letters. I can't reliably reproduce it though otherwise I'd open another issue...
